#!/usr/bin/env bash
#
# Script to tests Unicode case folding and decomposition
#
# Expects source.dmg to be generated by
# https://github.com/dfirlabs/hfs-specimens/blob/master/generate-specimens-unicode-macos.sh

EXIT_FAILURE=1;
EXIT_SUCCESS=0;

FSHFSINFO="fshfsinfo";

if test $# -ne 1;
then
	echo "Usage: test_unicode.sh source.dmg";
	echo "";

	exit ${EXIT_FAILURE};
fi

set -e

SOURCE=$1;

for FILE in `${FSHFSINFO} -o $(( 40 * 512 )) -H ${SOURCE} | grep '/testdir1/unicode_'`;
do
	echo "Testing: ${FILE}";

	NUMBER=`echo ${FILE} | sed 's/^.*unicode_U+/0x/;s/_.*$//'`;
	NUMBER=$(( ${NUMBER} ));

	# Handle / which was replaced by :
	if test ${NUMBER} -eq 58;
	then
		LOOKUP_PATH="/testdir1/unicode_U+0000003a_:";

	elif ( test ${NUMBER} -gt 0 && test ${NUMBER} -lt 55296 ) || test ${NUMBER} -ge 63744;
	then
		UNICODE_CHARACTER=`printf "%08x" $(( ${NUMBER} ))`;

		LOOKUP_PATH=`python2 -c "print(''.join(['/testdir1/unicode_U+${UNICODE_CHARACTER}_', '${UNICODE_CHARACTER}'.decode('hex').decode('utf-32-be')]).encode('utf-8'))"`;

	else
		LOOKUP_PATH=${FILE};
	fi

	OUTPUT=`${FSHFSINFO} -o $(( 40 * 512 )) -F ${LOOKUP_PATH} ${SOURCE} | grep 'Path' | sed 's/^.*: //'`;

	# Strip the actual Unicode character otherwise the name check will fail due the difference in composition
	COMPARE_FILE=`echo ${FILE} | sed 's/_[^_]*$//'`;
	COMPARE_OUTPUT=`echo ${OUTPUT} | sed 's/_[^_]*$//'`;

	if test "${COMPARE_FILE}" != "${COMPARE_OUTPUT}";
	then
		echo "Name mismatch: '${FILE}' != '${OUTPUT}'";
		echo "";

		exit ${EXIT_FAILURE};
	fi
done

